### ISSUE TITLE
proxy authentication

### ISSUE THREAD

**Issue by the-shank** [andrew-d/extika#6]
First up, thank you for the library. Its really helpful.

At work, we are behind a corporate proxy that requires authentication. The library is not detecting the username/password from the `http_proxy` and `https_proxy` environment variables. The proxy info in `http_proxy` is of the form `http://username:password@ip:port`.

On going through the code of `extika`, it looks like the proxy information derived from the env variables via the [`proxy_config()`](https://github.com/andrew-d/extika/blob/3307e4e7b530bb8257a020f11f9d767608447ad5/mix.exs#L134) function is useful for getting the ip and the port of the proxy.

From erlang's documentation on `httpc` [here](http://erlang.org/doc/man/httpc.html#request-5), it appears that the `proxy_auth` is to be passed with each request. In essence, it is required to grab the username/password from the proxy env variable (if present) and then set an option [here](https://github.com/andrew-d/extika/blob/3307e4e7b530bb8257a020f11f9d767608447ad5/mix.exs#L120) in `extika`.

If you like, I can send a pull request for this?

**Comment by the-shank** [comment]
@andrew-d

**Comment by andrew-d** [comment]
Hello!  Sorry, it looks like I missed the earlier notification; yes, if you'd like to submit a PR for this, I'd happily merge it :grinning:

**Comment by the-shank** [comment]
@andrew-d PR submitted. Please let me know if you would like to change anything.

**Comment by the-shank** [comment]
@andrew-d when possible, can you please push a new release to hex.

**Comment by andrew-d** [comment]
Tagged and pushed version v0.0.4!
